schema_version: 1

context:
  name: freeze-core
  version: "0.6.0"
  sha256: 46008c27e0e44bd97e283f2fb21df5190c555ff8dd2b008e6205f03f87f8c2c4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace("-", "_") }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  dynamic_linking:
    missing_dso_allowlist:
      - if: win
        then:
          - "**/cx_Logging.*.pyd"

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=78.1.1,<=82
    - if: win
      then:
        - cx_logging >=3.2
  run:
    - python
    - filelock >=3.20.3
    - if: win
      then:
        - cabarchive >=0.2.4
        - striprtf >=0.0.26
    - if: linux and match(python, "<3.11")
      then:
        - libxcrypt

tests:
  - python:
      imports:
        - freeze_core
  - files:
      source:
        - pyproject.toml
        - tests
    requirements:
      run:
        - coverage >=7.10.3
        - pytest >=9.0.2
    script:
      - coverage run

about:
  license: MIT
  license_file: LICENSE
  summary: Core dependency for cx_Freeze.
  repository: https://github.com/marcelotduarte/freeze-core
  homepage: https://marcelotduarte.github.io/cx_Freeze
  documentation: https://cx-freeze.readthedocs.io/

extra:
  recipe-maintainers:
    - marcelotduarte
